apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
  namespace: mindbox-sre-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaler-role
  namespace: mindbox-sre-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "deployments"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-rb
  namespace: mindbox-sre-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scaler-role
subjects:
  - kind: ServiceAccount
    name: scaler-sa
    namespace: mindbox-sre-test
